# Terminal title has to be set in ~/.bashrc because PS1 is a pile of crap
# Other local configuration can go here
# Append line to .bashrc:
# . "~/.cfg/local/bashrc"

# Automatically activate keras environment
conda activate keras
